version: "3.8"
services:
  db:
    image: postgres:15.2
    environment:
      - POSTGRES_MULTIPLE_DATABASES=iot_db,test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
    volumes:
      - postgres_data_iot:/var/lib/postgresql/data
      - ./create_multiple_db.sh:/docker-entrypoint-initdb.d/create_multiple_db.sh
    restart: unless-stopped # Hace que el contenedor se reinicie a menos que se detenga manualmente
    ports:
      - 5432:5432 # Puerto de postgres
  # Aqui el resto de servicios
volumes:
  postgres_data_iot:
